### PR TITLE
Add Dockerfile to make usage easier without installing additional req…

### PR DESCRIPTION
**Pull request by calebcase**
…uirements.

### CODE REVIEW

**Comment by calebcase** [comment]
CLA is signed, but it still shows here as not.

**Comment by calebcase** [comment]
Nevermind... apparently you just have to comment and it will recheck ;o]

**Comment by calebcase** [comment]
Would still be handy to have this.

**Comment by nemonster** [comment]
Can you elaborate on why you even need this considering you can run it remotely? If you do that you can run it from a workstation.

**Comment by calebcase** [comment]
@nemonster Sure! I run this from my own machine, but I don't want to install all those dependencies on my local machine. In particular, I don't otherwise have a for Java to be installed on this system.

IMHO, this makes it easier to provide reproducible environment to run the tool in that anyone with docker installed can use.

**Comment by nemonster** [comment]
Still not sure I understand. You don't install any dependencies. You download a zip, and if you have a JRE from 1.7 on installed (which is usually a default on most workstations) that's it. There isn't a reproducible environment involved unless you're counting unzipping the archive.

**Comment by calebcase** [comment]
I don't have a JRE installed so this helped me get it running without needing to install tools I wouldn't need except for when using this tool.

**Pull request closed without merging**
