### PR TITLE
Adds _alias output to the diagnostic dump

### PR DESCRIPTION
**Pull request by masaruh**
Sometimes it's useful especially when aliases have filter and/or routing.

### CODE REVIEW

**Comment by jjfalling** [comment]
looks like cluster state does not contain this data. ++ to adding it.

**Comment by jjfalling** [comment]
Actually, could you move this around where the settings are grabbed? I don't think we should need to get the aliases multiple times.

**Comment by masaruh** [comment]
Ah, true. Fixed.

**Comment by jjfalling** [comment]
looks good. also added to 2.0

**Pull request merged**
